version: '3'
services:
  simcraft-discord:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - simcraft-data:/simcraft-data
      - simcraft-logs:/root/.pm2/logs
    environment:
      - BATTLE_NET_KEY= # From https://dev.battle.net
      - DISCORD_KEY= # From https://discordapp.com/developers/applications/me
      - DEFAULT_REALM=Галакронд # Default realm
      - DEFAULT_ORIGIN=eu # Default origin
      - LOCALE=ru_RU # Default lang
      - TIMEZONE=Europe/Moscow # Default timezone
      - REPORTS_URL= # Url to report or empty if not need
    command: /bin/bash -c "envsubst < ecosystem.json > ecosystem.prod.json && pm2-docker start --auto-exit --env production ecosystem.prod.json"
  web:
    image: nginx
    volumes:
      - simcraft-reports:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/site.template
    ports:
      - "80:80"
    environment:
      - NGINX_HOST= # Host of report server
      - NGINX_PORT=80 # Server port
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
volumes:
  simcraft-data:
    external: true
  simcraft-reports:
    external: true
  simcraft-logs:
